#pragma config(Sensor, in1,    fieldPos,       sensorPotentiometer)
#pragma config(Sensor, in2,    side,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  catapult,       sensorQuadEncoder)
#pragma config(Sensor, dgtl12, cTouch,         sensorTouch)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port4,           leftCatapult,  tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port8,           rightCatapult, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rollers,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int d8Flag = 0;
int rollerSpeed = 0;
int toggleStateRoller = 0;
int encoderGoal = 110; // Higher for lower catapult
int idlePower = 10;

void autoShootFunction() {
	resetMotorEncoder(leftCatapult);
	if(SensorValue[cTouch] != 1) {
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 1);
		motor[leftCatapult] = motor[rightCatapult] = 0;
		wait1Msec(200);
		resetMotorEncoder(leftCatapult);
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 0 && getMotorEncoder(leftCatapult) >= (encoderGoal + 5));
		motor[leftCatapult] = motor[rightCatapult] = idlePower;
	} else {
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 0 && getMotorEncoder(leftCatapult) >= encoderGoal);
		motor[leftCatapult] = motor[rightCatapult] = idlePower;
	}

}

task autoShoot() {
	resetMotorEncoder(leftCatapult);
	if(SensorValue[cTouch] != 1) {
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 1);
		motor[leftCatapult] = motor[rightCatapult] = 0;
		wait1Msec(200);
		resetMotorEncoder(leftCatapult);
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 0 && getMotorEncoder(leftCatapult) >= (encoderGoal + 5));
		motor[leftCatapult] = motor[rightCatapult] = idlePower;
	} else {
		motor[leftCatapult] = motor[rightCatapult] = 127;
		waitUntil(SensorValue[cTouch] == 0 && getMotorEncoder(leftCatapult) >= encoderGoal);
		motor[leftCatapult] = motor[rightCatapult] = idlePower;
	}
}

void pre_auton()
{
	bStopTasksBetweenModes = true;
}



task autonomous() {
	if (SensorValue[fieldPos] > 2000) {
	}

		// Drive, Shoot, Get Low Flag, and then Return

}


// End of Auton Control ------------------------------------------------------------------------------------------------


// User Control ---------------------------------------------------------------------------------

task usercontrol() {

	while (1) {
		// Tank Drive / Dank Drive
		motor[frontLeft] = motor[backLeft] = vexRT[Ch3];
		motor[frontRight] = motor[backRight] = vexRT[Ch2];
		// --------------------------------------------------

		// Control Rollers
		// 8D for ON or OFF, 8L for reverse ON or OFF.
		if (vexRT[Btn8D] && !d8Flag) {
			rollerSpeed = (toggleStateRoller ? 127 : 0);
			toggleStateRoller = (toggleStateRoller ? 0 : 1);
		}

		if (vexRT[Btn8L] && !d8Flag) {
			rollerSpeed = (toggleStateRoller ? -127 : 0);
			toggleStateRoller = (toggleStateRoller ? 0 : 1);
		}

		if (vexRT[Btn8D] > 0) d8Flag = vexRT[Btn8D];
		else d8Flag = vexRT[Btn8L];
		motor[rollers] = rollerSpeed;
		// --------------------------------------------------

		// Catapult
		// 6O Shoot and pull back to correct value.
		if (vexRT[Btn6D]) {// && !d6Flag) {
			startTask(autoShoot);
		}
	}
}
		// --------------------------------------------------
