#pragma config(Sensor, in1,    auton,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightFront,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftFront,      sensorQuadEncoder)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port2,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftFront,     tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port6,           rightShoot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftShoot,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftArm,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightArm,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	resetMotorEncoder(leftBack);
	resetMotorEncoder(leftFront);
	//NOT NEAR FLAGS SPOT
	motor[leftShoot] = motor[rightShoot] = 127;
	motor[intake] = 127;
	wait1Msec(1000);
	motor[leftShoot] = motor[rightShoot] = 30;
	wait1Msec(1000);
	motor[leftShoot] = motor[rightShoot] = 127;
	motor[intake] = 0;
	wait1Msec(600);
	motor[leftShoot] = motor[rightShoot] = 0;
	if (SensorValue(auton)>1850)
	{
		motor[leftFront] = motor[leftBack] = -127;
		motor[rightFront] = motor[rightBack] = 127;
	}
	else
	{
		motor[leftFront] = motor[leftBack] = 127;
		motor[rightFront] = motor[rightBack] = -127;
	}
	wait1Msec(340);
	//move towards the cap
	if (SensorValue(auton)>1850)
	{
		motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	//wait1Msec(2000);
	waitUntil(getMotorEncoder(leftFront)>1250);
	//reached the cap
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(leftFront);
	//flip the cap
	motor[leftArm] = motor[rightArm] = 50;
	wait1Msec(1000);
	//return arm to normal position
	motor[leftArm] = motor[rightArm] = -80;
	wait1Msec(500);
	motor[leftArm] = motor[rightArm] = 0;
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	wait1Msec(300);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
}
else{
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	//wait1Msec(2000);
	waitUntil(getMotorEncoder(leftFront)>750);
	//reached the cap
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(leftFront);
	//flip the cap
	motor[leftArm] = motor[rightArm] = 50;
	wait1Msec(1000);
	//return arm to normal position
	motor[leftArm] = motor[rightArm] = -80;
	wait1Msec(1500);
	motor[leftArm] = motor[rightArm] = 0;
}

	//turn right to ram
	/*motor[leftFront] = motor[leftBack] = -127;
	motor[rightFront] = motor[rightBack] = 127;
	wait1Msec(300);
	resetMotorEncoder(leftFront);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	waitUntil(getMotorEncoder(leftFront)>400);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	resetMotorEncoder(leftFront);
	waitUntil(getMotorEncoder(leftFront)<-150);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	motor[leftBack]=motor[rightBack]=motor[rightFront]=motor[leftFront] = 0;
	resetMotorEncoder(leftFront);*/

	/*auton with potentiometer
	resetMotorEncoder(leftBack);
	resetMotorEncoder(leftFront);
	//NOT NEAR FLAGS SPOT
	motor[leftShoot] = motor[rightShoot] = 127;
	motor[intake] = 127;
	wait1Msec(1000);
	motor[leftShoot] = motor[rightShoot] = 30;
	wait1Msec(1000);
	motor[leftShoot] = motor[rightShoot] = 127;
	motor[intake] = 0;
	wait1Msec(600);
	motor[leftShoot] = motor[rightShoot] = 0;

	motor[leftFront] = motor[leftBack] = 127;
	motor[rightFront] = motor[rightBack] = -127;
	wait1Msec(500);
	//move towards the cap
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	//wait1Msec(2000);
	waitUntil(getMotorEncoder(leftFront)>900);
	//reached the cap
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(leftFront);
	//flip the cap
	motor[leftArm] = motor[rightArm] = 80;
	wait1Msec(1000);
	//return arm to normal position
	motor[leftArm] = motor[rightArm] = -80;
	wait1Msec(1500);
	motor[leftArm] = motor[rightArm] = 0;
	//turn right to ram
	motor[leftFront] = motor[leftBack] = 127;
	motor[rightFront] = motor[rightBack] = -127;
	wait1Msec(400);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	waitUntil(getMotorEncoder(leftFront)>400);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	resetMotorEncoder(leftFront);
	waitUntil(getMotorEncoder(leftFront)>150);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	*/





	/*
	//AUTON NUMBER 1 NEAR FLAGS SPOT
	//if(SensorValue[auton] > 1850)
	//{
	//prep the shooter

	motor[leftShoot] = motor[rightShoot] = 127;
	//robot move forward to hit flag
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	//wait1Msec(500);
	waitUntil(getMotorEncoder(rightFront)>500);
	//constant shooter
	motor[leftShoot] = motor[rightShoot] = 20;
	//load the ball
	motor[intake] = 127;
	resetMotorEncoder(rightFront);
	//wait1Msec(1000);
	waitUntil(getMotorEncoder(rightFront)>1000);
	//robot has hit flag
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(rightFront);
	//move back to shoot ball
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	//wait1Msec(1000);
	waitUntil(getMotorEncoder(rightFront)>100);
	//ball is loaded and ready to fire
	motor[intake] = 0;
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(rightFront);
	wait1Msec(150);
	//fire ball
	motor[leftShoot] = motor[rightShoot] = 127;
	wait1Msec(1000);
	//ball has hit flag
	motor[leftShoot] = motor[rightShoot] = 0;
	//move back to original position
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	//wait1Msec(1000);
	waitUntil(getMotorEncoder(rightFront)>1000);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(rightFront);
	//turn right-- we are part of red alliance
	motor[leftFront] = motor[leftBack] = 127;
	motor[rightFront] = motor[rightBack] = -127;
	wait1Msec(750);
	//ready to go for the gold
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	//wait1Msec(10000);
	waitUntil(getMotorEncoder(rightFront)>10000);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	resetMotorEncoder(rightFront);
	*/

	/*
	IF BALL FITS INTO HOLE AND WE DON'T NEED INTAKE
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	wait1Msec(500);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	motor[leftShoot] = motor[rightShoot] = 127;
	wait1Msec(2000);
	motor[leftShoot] = motor[rightShoot] = 0;
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	wait1Msec(2000);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	wait1Msec(3000);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	*/


	/*
	ESHAAN'S AUTONOMOUS
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = -127;
	wait1Msec(2000);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	motor[arm]= 127;
	wait1Msec(500);
	motor[arm]= 0;
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 127;
	wait1Msec(400);
	motor[leftFront] = motor[leftBack] = motor[rightFront] = motor[rightBack] = 0;
	*/
	//}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
int rightDriveValue;
int leftDriveValue;

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		leftDriveValue = vexRT[Ch3] + vexRT[Ch4];
		rightDriveValue = vexRT[Ch3] - vexRT[Ch4];

		motor[leftFront] = motor[leftBack] = leftDriveValue;
		motor[rightFront] = motor[rightBack] = rightDriveValue;

		motor[leftArm] = motor[rightArm] = (vexRT[Btn6U] - vexRT[Btn6D]) * 60;

		motor[leftShoot] = motor[rightShoot] = (vexRT[Btn8D] * 60) + 20;

		motor[intake] = (vexRT[Btn5U] - vexRT[Btn5D]) *127;

	}
}
